### PR TITLE
typescirpt

### PR DESCRIPTION
**Pull request by trinkey**
## What does this do?
turns all javascript into typescript, fixes a bug with viewing profiles, and rewrites all html

## Issues completed:
- #186 

---
### Checklist for Reviewers
- [x] Version has been incremented (if appropriate)
- [x] BACKEND.md has been updated for any new functions
- [x] Any new changes have been tested thoroughly (including api calls that wouldn't normally be possible using inspect element or the /api/docs page)
- [x] Any changes have been documented in the `changelog.logs` part of the en-US language file, along with the minor language version being incremented
- [x] Features that break easily have been tested (mostly viewing pages when not logged in)

### CODE REVIEW

**Comment by trinkey** [comment]
pushed to stealyourip @Subroutine7901 you should reveiew and test big

**Comment by Subroutine7901** [comment]
Ok but I'm skipping over ts files bc I dont know the lang

**Comment by trinkey** [comment]
> I'm skipping over ts files

so... the whole pr?

**Comment by trinkey** [comment]
the js is autogenerated and everything else works fine

**Review by Subroutine7901 — COMMENTED** [review]
All the code exc. typescript looks good, haven't done testing so I'll do that in a bit. A list of what to test would be useful if its not literally everything js

**Comment by trinkey** [comment]
what needs to be tested is basically anything frontend that involves javascript

**Review by DiamondTaco — APPROVED** [review]
doesn't lgtm

**Pull request merged**
