### PR TITLE
more backend settings

### LINKED ISSUE #168: add more backend settings
could have:
- disabling certain settings individually, ex:
  - pronouns
  - gradient banners
  - badges
  - bios
- bigger features, ex:
  - messaging
  - quoting
  - timestamps

a lot of these are just like why would you want to disable them but also there might be that one person who will be like "YESSS I CAN DISABLE GRADIENTS ON MY INSTANCE W"

### PR DESCRIPTION
**Pull request by trinkey**
## What does this do?
adds more backend settings
- ENABLE_USER_BIOS
- ENABLE_PRONOUNS
- ENABLE_GRADIENT_BANNERS
- ENABLE_BADGES
- ENABLE_PRIVATE_MESSAGES
- ENABLE_QUOTES
- ENABLE_POST_DELETION

## Issues completed:
- fixes #168

---
### Checklist for Reviewers
- [x] Version has been incremented (if appropriate)
- [x] BACKEND.md has been updated for any new functions
- [x] Code is formatted good enough (ask @trinkey)
- [x] Any new changes have been tested thoroughly (including api calls that wouldn't normally be possible using inspect element or using the /api/docs page)
- [x] Features that break easily have been tested (mostly viewing pages when not logged in)

### CODE REVIEW

**Comment by trinkey** [comment]
@Subroutine7901 please review

**Comment by Subroutine7901** [comment]
Ok so the hitbox on this is broken, idk if it's related to bios or not but yk
image
Also maybe remove the section from the admin page for post deletion like the badge section got removed when deletion is disabled.

**Review by Subroutine7901 — DISMISSED** [review]
https://github.com/jerimiah-smiggins/smiggins/pull/171#issuecomment-2106101929 (I didn't put it in the right place :3)

**Comment by trinkey** [comment]
> > the hitbox on this is broken, idk if it's related to bios or not but yk
> 
> 
> ik its not hard i just haven't felt like it
> 
> also admin thing good idea

i accidentally edited this instead of quoting it lol

**Review by Subroutine7901 — APPROVED** [review]
Trinkey fixed the problems?!?!? - impossible!!!

**Pull request merged**
