### PR TITLE
Invite codes

### LINKED ISSUE #201: un "View results" on polls
need to add a way to go back to the voting stage to make it less confusing

### LINKED ISSUE #262: one time invite codes for signups
Okay, so let's say, hypothetically, that I make a cat club on smiggins (the best cat club platform) but goofy dog club members find the link to my cat club site and start mass-enrolling accounts. Is there a way to set a password before a user could create an account, to keep it members-only?

### PR DESCRIPTION
**Pull request by trinkey**
## What does this do?
Creates a way to manage who is allowed to sign up by using one-time invite codes that can be generated on the admin page.

## Issues completed:
- fixes #262 
- fixes #201 

---
### Checklist for Reviewers
- [x] Version has been incremented (if appropriate) on the `REAL_VERSION` variable in `backend/variables.py`
- [x] Any new changes have been tested thoroughly (including api calls that wouldn't normally be possible using inspect element or the /api/docs page)
- [x] Any changes have been documented in `CHANGELOG.md`
- [x] Features that break easily have been tested (mostly viewing pages when not logged in)

### CODE REVIEW

**Comment by trinkey** [comment]
> if its on smiggins, there's a pull request the next day

we don't talk about #192

**Comment by Subroutine7901** [comment]
I should do this shouldn't I

**Comment by Subroutine7901** [comment]
> if its on smiggins, there's a pull request the next day
yeah but I'll get to reviewing it in like 2 weeks

**Review by Subroutine7901 — APPROVED** [review]
Everything looks good, although I wasn't about to test the backend setting related stuff... Test in production amiright?

**Pull request merged**
