### PR TITLE
commit aarggh

### LINKED ISSUE #237: make ninja /api/docs useful

### LINKED ISSUE #244: custom themes

### PR DESCRIPTION
**Pull request by trinkey**
## What does this do?
api definition rewrite and custom themes

- [x] dynamic theme definitions in settings
- [ ] setting a custom theme in settings
- [x] favicons with custom themes

## Issues completed:
- fixes #237
- fixes #244 

---
### Checklist for Reviewers
- [x] Version has been incremented (if appropriate) on the `REAL_VERSION` variable in `backend/variables.py`
- [x] Any new changes have been tested thoroughly (including api calls that wouldn't normally be possible using inspect element or the /api/docs page)
- [x] Any changes have been documented in the `changelog.logs` part of the en-US language file, along with the minor language version being incremented
- [x] Features that break easily have been tested (mostly viewing pages when not logged in)

### CODE REVIEW

**Comment by trinkey** [comment]
i think i'm gonna push the custom theme via frontend to a later date it already works perfectly good as it is

**Review by Subroutine7901 — CHANGES_REQUESTED** [review]
I love the API changes. The new themes also look really nice, and the CSS changes that I looked at in the code look good. The restructuring of API.py is good aswell. The only issue is that the content warnings don't cover quotes as you said they would. That and I guess there's something wrong with the checkboxes, but that's minor enough I wouldn't bother about it right now.

**Comment by trinkey** [comment]
checkboxes work, probably lack of browser support for :has() on your end (this is why the disable custom checkboxes option exists) but yes the quote thing is intentional i forgot to reflect it in the changelog

**Comment by Subroutine7901** [comment]
Okay great, checkbox I did not explain, as it's extremely minor. The custom ones do work, but there is one exception, which is that checkbox that toggles custom checkboxes. If I toggle it on then off, then all the boxes but that one will be custom, so it's like one box and/or a reload. Not very important.

**Pull request merged**
