### PR TITLE
polls

### LINKED ISSUE #105: polls

### LINKED ISSUE #184: auto post webhooks
add an option backend to send a request to a webhook when a post by a specified user is made, or by anyone, and it can be configured to include posts/quotes and/or comments

### LINKED ISSUE #188: even MORE backend options
- disable changelog
- disable contact page
- disable polls (when #187 gets merged)
- disable pins
- disable account switcher
- disable signing up completely (will need to be indicated on the index page and signup page when not logged in)
- disable viewing content when logged out

### LINKED ISSUE #190: issues loading posts
user pages don't load the last page
recent tab skips 10 posts
following tab seems fine

### PR DESCRIPTION
**Pull request by trinkey**
## What does this do?
adds polls and adds an option to the backend that automatically sends a webhook to the specified url when someone with a username makes a post, and adds a bunch more backend toggles

## Issues completed:
- fixes #105
- fixes #184
- fixes #188 
- fixes #190 

---
### Checklist for Reviewers
- [x] Version has been incremented (if appropriate)
- [x] BACKEND.md has been updated for any new functions
- [x] Any new changes have been tested thoroughly (including api calls that wouldn't normally be possible using inspect element or the /api/docs page)
- [x] Any changes have been documented in the `changelog.logs` part of the en-US language file, along with the minor language version being incremented
- [x] Features that break easily have been tested (mostly viewing pages when not logged in)

### CODE REVIEW

**Comment by Subroutine7901** [comment]
ok uh
I open a post (.com/p/number)
I vote
I go back with the browser's back button
poll no have vote on home page
I click?
nothing
I reload
now the results and my vote show up
huh
also there's an issue with the account switcher so maybe make it so if you switch to an account it deletes it and then logs you out like you were adding a new account instead of just logging out for a new account that'd be good
It also had another thing so just play around with switching to a deleted account

**Comment by trinkey** [comment]
> I go back with the browser's back button
> poll no have vote on home page

this is a browser caching issue not a smiggins issue, no way to easily fix this

**Comment by trinkey** [comment]
> also there's an issue with the account switcher

i didn't change much besides adding a toggle? i can check though

**Comment by trinkey** [comment]
oh you're talking about switching to a deleted account i get it

fixing that would require rewriting a bunch of the account switcher functionality and i don't want to worry about that

in general switching to a deleted account should happen almost never unless someone messed

**Comment by trinkey** [comment]
someone should review my pr (@subroutine)

**Comment by Subroutine7901** [comment]
All the issues I talked about were addressed so I guess its good

**Review by Subroutine7901 — APPROVED** [review]
Started falling asleep, its 2am, ims eepy
Looked good
Gn

**Pull request merged**
